import React, { useState, useEffect } from 'react';
import { 
  Sparkles, 
  Calendar, 
  Clock, 
  BookOpen, 
  HelpCircle,
  Activity,
  Award
} from 'lucide-react';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import NotificationToast from '../components/NotificationToast';

const CustomerRemedies = () => {
  const { profile } = useAuth();
  const [consultations, setConsultations] = useState([]);
  const [aiInsights, setAiInsights] = useState('');
  const [aiLoading, setAiLoading] = useState(false);
  const [loading, setLoading] = useState(true);
  const [toast, setToast] = useState(null);

  const fetchConsultationsHistory = async () => {
    if (!profile) {
      setLoading(false);
      return;
    }

    setLoading(true);
    try {
      const response = await api.get('/consultations');
      if (response.data.success) {
        setConsultations(response.data.data);
        
        // Find if any consultation contains generated AI insights
        const latestWithInsights = response.data.data.find(c => c.aiClientInsights);
        if (latestWithInsights) {
          setAiInsights(latestWithInsights.aiClientInsights);
        }
      }
    } catch (error) {
      console.error('Failed to load consultation history:', error);
      setToast({ type: 'error', message: 'Failed to load consultation history.' });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchConsultationsHistory();
  }, [profile]);

  const handleGenerateAIInsights = async () => {
    if (!profile) return;
    setAiLoading(true);
    try {
      const response = await api.post('/consultations/ai/insights', { clientId: profile._id });
      if (response.data.success) {
        setAiInsights(response.data.data);
        setToast({ type: 'success', message: 'AI insights generated successfully!' });
      }
    } catch (error) {
      console.error('Error generating client insights:', error);
      setToast({ 
        type: 'error', 
        message: error.response?.data?.message || 'Failed to generate AI insights. Try again.' 
      });
    } finally {
      setAiLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="h-64 flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-indigo-500"></div>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-8 max-w-4xl mx-auto">
      {/* Page Title */}
      <div className="border-b border-white/5 pb-4">
        <h3 className="text-xl font-bold text-gray-100">My Remedies & AI Predictions</h3>
        <p className="text-xs text-gray-400 mt-0.5">Read remedies, planetary transits, and predictions generated by your astrologer and AI engines</p>
      </div>

      {/* AI Chart Summary Panel */}
      {profile && (
        <div className="glass-panel border border-white/5 rounded-3xl p-6 relative overflow-hidden flex flex-col gap-5">
          <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/10 rounded-full blur-2xl pointer-events-none" />
          <div className="absolute left-1/4 bottom-0 w-24 h-24 bg-purple-500/5 rounded-full blur-xl pointer-events-none" />

          <div className="flex items-center justify-between border-b border-white/5 pb-4">
            <div className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-indigo-400 animate-pulse" />
              <div>
                <h4 className="font-bold text-gray-200 text-sm tracking-wide">AI Natal Chart Analysis</h4>
                <p className="text-[10px] text-gray-500">Planetary alignments and personality factors</p>
              </div>
            </div>
            <button
              onClick={handleGenerateAIInsights}
              disabled={aiLoading}
              className="px-3.5 py-1.5 bg-slate-800/80 border border-white/5 hover:border-indigo-500/30 rounded-xl text-xs text-indigo-400 hover:text-indigo-300 font-semibold cursor-pointer disabled:opacity-50 flex items-center gap-1.5 transition-all"
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>{aiLoading ? 'Analyzing Chart...' : 'Generate Analysis'}</span>
            </button>
          </div>

          {aiLoading ? (
            <div className="flex flex-col gap-3 py-6 animate-pulse">
              <div className="h-3 bg-slate-800 rounded w-full"></div>
              <div className="h-3 bg-slate-800 rounded w-5/6"></div>
              <div className="h-3 bg-slate-800 rounded w-2/3"></div>
            </div>
          ) : aiInsights ? (
            <div className="bg-slate-950/20 border border-white/5 p-4 rounded-2xl">
              <p className="text-xs text-gray-400 leading-relaxed whitespace-pre-line">
                {aiInsights}
              </p>
            </div>
          ) : (
            <div className="py-6 text-center text-xs text-gray-500">
              No natal insights generated yet. Click "Generate Analysis" to run a planetary alignment check.
            </div>
          )}
        </div>
      )}

      {/* Timeline of consultations */}
      <div className="glass-panel border border-white/5 rounded-3xl p-6">
        <h4 className="font-bold text-gray-200 text-sm tracking-wide border-b border-white/5 pb-4 mb-4">Consultation Timeline & Remedies</h4>

        <div className="flex flex-col gap-8">
          {consultations.length === 0 ? (
            <div className="py-12 text-center text-xs text-gray-500 flex flex-col gap-2 items-center">
              <HelpCircle className="w-10 h-10 text-gray-600" />
              <span>No logged consultation summaries are available yet.</span>
              <p className="text-[10px] text-gray-600 max-w-xs leading-relaxed mt-1">
                Your remedies and prediction summaries will appear here once your astrologer logs your first completed session.
              </p>
            </div>
          ) : (
            consultations.map((consult, index) => (
              <div key={consult._id} className="relative pl-6 border-l border-white/10 flex flex-col gap-4">
                {/* Ring node */}
                <span className="absolute -left-1.5 top-1.5 w-3 h-3 rounded-full bg-[#090d16] border-2 border-indigo-500" />
                
                <div className="flex flex-col gap-3">
                  {/* Session Header */}
                  <div className="flex items-center justify-between flex-wrap gap-2">
                    <div className="flex items-center gap-2.5">
                      <span className="text-xs font-bold text-gray-200">Session #{consultations.length - index}</span>
                      <span className="px-2 py-0.5 bg-indigo-500/10 border border-indigo-500/20 rounded text-[9px] uppercase font-bold text-indigo-300 tracking-wider">
                        {consult.type}
                      </span>
                    </div>
                    <span className="text-xs text-gray-500 font-semibold flex items-center gap-1.5">
                      <Calendar className="w-3.5 h-3.5" />
                      {new Date(consult.date).toLocaleDateString()}
                    </span>
                  </div>

                  {/* Consultation Body Card */}
                  <div className="bg-slate-950/20 border border-white/5 rounded-2xl p-5 flex flex-col gap-4">
                    {/* General Notes */}
                    <div>
                      <span className="text-[9px] text-gray-500 font-bold uppercase tracking-wider block">Astrological Notes</span>
                      <p className="text-xs text-gray-300 mt-1 leading-relaxed whitespace-pre-line">{consult.notes}</p>
                    </div>

                    {/* Predictions */}
                    {consult.predictions && (
                      <div className="border-t border-white/5 pt-3">
                        <span className="text-[9px] text-gray-500 font-bold uppercase tracking-wider block">Personalized Predictions</span>
                        <p className="text-xs text-gray-300 mt-1 leading-relaxed whitespace-pre-line">{consult.predictions}</p>
                      </div>
                    )}

                    {/* Remedies Suggested */}
                    {consult.remediesSuggested && (
                      <div className="border-t border-white/5 pt-3">
                        <span className="text-[9px] text-indigo-400 font-bold uppercase tracking-wider block">Suggested Remedies & Gemstones</span>
                        <p className="text-xs text-indigo-200 mt-1 leading-relaxed whitespace-pre-line font-medium">{consult.remediesSuggested}</p>
                      </div>
                    )}

                    {/* Follow up date info */}
                    {consult.followUpDate && (
                      <div className="flex items-center gap-2 mt-2 pt-2 border-t border-white/5 text-[9px] text-indigo-400 font-semibold uppercase tracking-wider">
                        <Clock className="w-3.5 h-3.5" />
                        <span>Recommended Follow-up: {new Date(consult.followUpDate).toLocaleDateString()}</span>
                      </div>
                    )}
                  </div>

                  {/* AI Summary */}
                  {consult.aiSummary && (
                    <div className="bg-indigo-600/5 border border-indigo-500/10 rounded-2xl p-4">
                      <div className="flex items-center gap-1.5 text-indigo-400">
                        <Sparkles className="w-3.5 h-3.5 animate-pulse" />
                        <span className="text-[9px] font-bold uppercase tracking-wider">AI Consultation Summary</span>
                      </div>
                      <p className="text-xs text-indigo-200/80 mt-1.5 leading-relaxed">{consult.aiSummary}</p>
                    </div>
                  )}
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {toast && (
        <NotificationToast
          message={toast.message}
          type={toast.type}
          onClose={() => setToast(null)}
        />
      )}
    </div>
  );
};

export default CustomerRemedies;
